FROM ubuntu:14.04
MAINTAINER GuangZhou "guang-zhou.zhou@hpe.com"
ENV http_proxy http://proxy.houston.hpecorp.net:8080
ENV https_proxy https://proxy.houston.hpecorp.net:8080
COPY test.txt /tmp/
ADD test /tmp/

WORKDIR /opt/chatui/
ADD test /opt/chatui/

#RUN export http_proxy=http://proxy.houston.hpecorp.net:8080
#RUN export https_proxy=https://proxy.houston.hpecorp.net:8080
#RUN apt-get update \
#    && apt-get install -y nginx
#RUN echo 'Hi, I am in your container'
CMD ["/bin/echo","this is a echo test"]



#ENTRYPOINT ls -l
#ENTRYPOINT ["memcached"]
#USER root
ADD test /etc/
EXPOSE 13080
#EXPOSE 80